### PR TITLE
Load methods before lifecycle hooks

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
Entire file: https://github.com/smile-io/ember-styleguide/blob/625da65b7d9310a3ef4945a0bec195c5b2857c62/.eslintrc.js

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
Whenever I had to use functions inside a route, it was a function that was invoked from one of those hooks. 

I usually like to have methods I use declared above the functions its being invoked from. Are there other types of functions that don't fit into what I've described? (ie apart from the ones already mentioned in that array)

**Comment by andrewpye** [comment]
>I usually like to have methods I use declared above the functions its being invoked from

I guess we have differing opinions then 😅 To me it makes sense to have the "coarse" logic first so you quickly get a feel for what's happening in the file (assuming things are named clearly 😉), then drill down into the detail as you scroll down through the file 🤷‍♂️

**Comment by sivakumar-kailasam** [comment]
Ah I was thinking of functions & not methods when I wrote that. My bad. I follow the same pattern that you described for methods on classes. Modified the PR for it.

**Comment by andrewpye** [comment]
Wait, how's this linter config distinguishing between `function` and `method`?! 😕

**Comment by sivakumar-kailasam** [comment]
It wouldn't afaict. functions would be written outside the class blueprint/object so they're not considered to be a part of this rule. Also we tend to move it to their own utils most of the time.

**Comment by andrewpye** [comment]
Yeah that was my thinking 😛

**Pull request merged**
